### ISSUE TITLE
Does not work on Ubuntu 18.04

### ISSUE THREAD

**Issue by fsevenm** [atareao/nautilus-copypaste-images#2]
I had been successfully installed this extension, I restarted my nautilus with 
`nautilus -q`
But I could not see the option.
Any idea why this extension cannot run?

**Comment by geoolekom** [comment]
I have the same problem. 

When I run nautilus within console, I see exceptions:
```bash
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-copypaste-images.py", line 118, in get_file_items
    label=SEPARATOR)
NameError: global name 'SEPARATOR' is not defined
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-copypaste-images.py", line 101, in get_file_items
    if self.all_files_are_images(sel_items):
  File "/usr/share/nautilus-python/extensions/nautilus-copypaste-images.py", line 82, in all_files_are_images
    if fileExtension.lower() not in EXTENSIONS:
NameError: global name 'EXTENSIONS' is not defined
```
I see that this bug is already fixed. However, it seems that fix hasn't affected ppa.

**Comment by geoolekom** [comment]
@fsevenm You should replace your plugin file with the one from repository. 
The local path is like "/usr/share/nautilus-python/extensions/nautilus-copypaste-images.py"

**Comment by digeomel** [comment]
I cannot even install the plugin in Ubuntu 22.04.2 LTS. Is this still supposed to work? I can see that it hasn't been updated for years, but it's a pity because this is such a basic functionality to have and a lot of people would appreciate it.
